#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tumbler
Version  : 0.1.31
Release  : 1
URL      : http://archive.xfce.org/src/xfce/tumbler/0.1/tumbler-0.1.31.tar.bz2
Source0  : http://archive.xfce.org/src/xfce/tumbler/0.1/tumbler-0.1.31.tar.bz2
Summary  : Supporting library for tumbler
Group    : Development/Tools
License  : GPL-2.0
Requires: tumbler-lib
Requires: tumbler-data
Requires: tumbler-doc
Requires: tumbler-locales
BuildRequires : docbook-xml
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(gthread-2.0)

%description
What is this?
=============
Tumbler is a D-Bus service for applications to request thumbnails for
various URI schemes and MIME types. It is an implementation of the
thumbnail management D-Bus specification described on

%package data
Summary: data components for the tumbler package.
Group: Data

%description data
data components for the tumbler package.


%package dev
Summary: dev components for the tumbler package.
Group: Development
Requires: tumbler-lib
Requires: tumbler-data
Provides: tumbler-devel

%description dev
dev components for the tumbler package.


%package doc
Summary: doc components for the tumbler package.
Group: Documentation

%description doc
doc components for the tumbler package.


%package lib
Summary: lib components for the tumbler package.
Group: Libraries
Requires: tumbler-data

%description lib
lib components for the tumbler package.


%package locales
Summary: locales components for the tumbler package.
Group: Default

%description locales
locales components for the tumbler package.


%prep
%setup -q -n tumbler-0.1.31

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install
%find_lang tumbler

%files
%defattr(-,root,root,-)
/usr/lib64/tumbler-1/tumblerd

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/services/org.xfce.Tumbler.Cache1.service
/usr/share/dbus-1/services/org.xfce.Tumbler.Manager1.service
/usr/share/dbus-1/services/org.xfce.Tumbler.Thumbnailer1.service

%files dev
%defattr(-,root,root,-)
/usr/include/tumbler-1/tumbler/tumbler-abstract-thumbnailer.h
/usr/include/tumbler-1/tumbler/tumbler-cache-plugin.h
/usr/include/tumbler-1/tumbler/tumbler-cache.h
/usr/include/tumbler-1/tumbler/tumbler-config.h
/usr/include/tumbler-1/tumbler/tumbler-enum-types.h
/usr/include/tumbler-1/tumbler/tumbler-error.h
/usr/include/tumbler-1/tumbler/tumbler-file-info.h
/usr/include/tumbler-1/tumbler/tumbler-glib-extensions.h
/usr/include/tumbler-1/tumbler/tumbler-marshal.h
/usr/include/tumbler-1/tumbler/tumbler-provider-factory.h
/usr/include/tumbler-1/tumbler/tumbler-provider-plugin.h
/usr/include/tumbler-1/tumbler/tumbler-thumbnail-flavor.h
/usr/include/tumbler-1/tumbler/tumbler-thumbnail.h
/usr/include/tumbler-1/tumbler/tumbler-thumbnailer-provider.h
/usr/include/tumbler-1/tumbler/tumbler-thumbnailer.h
/usr/include/tumbler-1/tumbler/tumbler-util.h
/usr/include/tumbler-1/tumbler/tumbler.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
/usr/share/gtk-doc/html/tumbler/TumblerAbstractThumbnailer.html
/usr/share/gtk-doc/html/tumbler/TumblerCache.html
/usr/share/gtk-doc/html/tumbler/TumblerThumbnail.html
/usr/share/gtk-doc/html/tumbler/TumblerThumbnailerProvider.html
/usr/share/gtk-doc/html/tumbler/api-index-full.html
/usr/share/gtk-doc/html/tumbler/extension-api.html
/usr/share/gtk-doc/html/tumbler/extension-tutorial.html
/usr/share/gtk-doc/html/tumbler/home.png
/usr/share/gtk-doc/html/tumbler/index.html
/usr/share/gtk-doc/html/tumbler/index.sgml
/usr/share/gtk-doc/html/tumbler/left-insensitive.png
/usr/share/gtk-doc/html/tumbler/left.png
/usr/share/gtk-doc/html/tumbler/miscellaneous.html
/usr/share/gtk-doc/html/tumbler/object-tree.html
/usr/share/gtk-doc/html/tumbler/pt01.html
/usr/share/gtk-doc/html/tumbler/right-insensitive.png
/usr/share/gtk-doc/html/tumbler/right.png
/usr/share/gtk-doc/html/tumbler/style.css
/usr/share/gtk-doc/html/tumbler/thumbnails.html
/usr/share/gtk-doc/html/tumbler/tumbler-Error-Domain-and-Types.html
/usr/share/gtk-doc/html/tumbler/tumbler-Various-Enumeration-Types.html
/usr/share/gtk-doc/html/tumbler/tumbler-Version-Information-and-Compatibility-Checks.html
/usr/share/gtk-doc/html/tumbler/tumbler-tumbler-file-info.html
/usr/share/gtk-doc/html/tumbler/tumbler-tumbler-provider-factory.html
/usr/share/gtk-doc/html/tumbler/tumbler-tumbler-provider-plugin.html
/usr/share/gtk-doc/html/tumbler/tumbler.devhelp2
/usr/share/gtk-doc/html/tumbler/up-insensitive.png
/usr/share/gtk-doc/html/tumbler/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*

%files locales -f tumbler.lang 
%defattr(-,root,root,-)

